name: Update LeetCode Progress

on:
  schedule:
    - cron: '0 0 * * *'    # every day at midnight UTC
  workflow_dispatch:      # manual trigger

jobs:
  update-leetcode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate LeetCode stats
        uses: meugenom/github-leetcode-stats@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leetcode_username: dimit999d  # ← replace with your handle
          readme_path: README.md

      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update LeetCode stats'
          add: 'README.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
