name: Update LeetCode Progress

on:
  schedule:
    - cron: '0 0 * * *'    # every day at midnight UTC
  workflow_dispatch:      # manual trigger

jobs:
  update-leetcode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate LeetCode stats
        uses: meugenom/github-leetcode-stats@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leetcode_session: ${{ secrets.LEETCODE_SESSION }}
          csrf_token: ${{ secrets.CSRF_TOKEN }}
          readme_path: README.md

      - name: Commit updated README
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          message: 'chore: update LeetCode stats'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
